In [2]:
import pandas as pd

df= pd.read_csv("Teen_Mental_Health_Dataset.csv")
df.head(10)

df.info()
df.describe()
df.isnull().sum()

print(df["gender"].unique())
print(df["platform_usage"].unique())
print(df["social_interaction_level"].unique())

df["gender"] = df["gender"].str.capitalize()
print(df["gender"].unique())

df["social_interaction_level"]= df["social_interaction_level"].str.capitalize()
print(df["social_interaction_level"].unique())
#Erika, veo que no ejecuta bien la orden en "gender", busco solucion y encunetro:

df["gender"]= df["gender"].apply(lambda x: x.capitalize())
print(df["gender"].unique())
# Aprendo a volver a guardar los datos limpios de nuevo en el csv.(Esto es nuevo para mi)

df.to_csv("Teen_Mental_Health_Dataset.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 122.0 KB
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
<StringArray>
['Instagram', 'TikTok', 'Both']
Length: 3, dtype: str
<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [3]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,Male,7.9,Instagram,7.4,2.9,3.01,1.5,Low,2,2,1,0
1,19,Female,1.9,TikTok,8.0,2.9,3.22,0.8,High,8,1,10,0
2,17,Female,1.3,Instagram,7.6,0.5,3.92,0.0,High,2,4,2,0
3,15,Male,7.4,TikTok,6.9,1.6,3.48,0.8,Medium,1,7,9,0
4,15,Female,4.7,Both,4.9,3.0,2.37,1.4,Medium,3,5,2,0

In [ ]:
#Vamos a comprobar si tenemos duplicados. 

df.duplicated().sum() #EL resultado nos dice que no hay filas duplicadas, por lo que los datos estan limpios.

np.int64(0)

In [8]:
#Crear la columna primary key - indice de adolescente. 

adolescente_id = df["adolescente_id"] = range(1, len(df) + 1)
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,adolescente_id
0,14,Male,7.9,Instagram,7.4,2.9,3.01,1.5,Low,2,2,1,0,1
1,19,Female,1.9,TikTok,8.0,2.9,3.22,0.8,High,8,1,10,0,2
2,17,Female,1.3,Instagram,7.6,0.5,3.92,0.0,High,2,4,2,0,3
3,15,Male,7.4,TikTok,6.9,1.6,3.48,0.8,Medium,1,7,9,0,4
4,15,Female,4.7,Both,4.9,3.0,2.37,1.4,Medium,3,5,2,0,5

In [12]:
#Dividir dataframe en 3 tablas
#1. Tabla adolescente: 

adolescentes = df[['adolescente_id', 'age', 'gender']]
adolescentes

      adolescente_id  age  gender
0                  1   14    Male
1                  2   19  Female
2                  3   17  Female
3                  4   15    Male
4                  5   15  Female
...              ...  ...     ...
1195            1196   18  Female
1196            1197   16    Male
1197            1198   14  Female
1198            1199   15    Male
1199            1200   16  Female

[1200 rows x 3 columns]

In [14]:
#2. Tabla comportamiento_uso:

comportamiento_uso = df[['adolescente_id', 'daily_social_media_hours', 'platform_usage', 'screen_time_before_sleep']]
comportamiento_uso

,adolescente_id,daily_social_media_hours,platform_usage,screen_time_before_sleep
0,1,7.9,Instagram,2.9
1,2,1.9,TikTok,2.9
2,3,1.3,Instagram,0.5
3,4,7.4,TikTok,1.6
4,5,4.7,Both,3.0
...,...,...,...,...
1195,1196,6.8,Instagram,2.0
1196,1197,2.3,Both,1.9
1197,1198,1.7,Both,0.7
1198,1199,3.9,Both,2.1
1199,1200,4.7,TikTok,1.0

In [17]:
# Tabla salud_rendimiento:

salud_rendimiento = df[['adolescente_id', 'sleep_hours', 'academic_performance', 'physical_activity', 'social_interaction_level', 'stress_level', 'anxiety_level', 'addiction_level', 'depression_label']]
salud_rendimiento

,adolescente_id,sleep_hours,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,1,7.4,3.01,1.5,Low,2,2,1,0
1,2,8.0,3.22,0.8,High,8,1,10,0
2,3,7.6,3.92,0.0,High,2,4,2,0
3,4,6.9,3.48,0.8,Medium,1,7,9,0
4,5,4.9,2.37,1.4,Medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...
1195,1196,6.6,2.76,1.0,Low,3,4,4,0
1196,1197,8.0,2.12,0.4,High,7,4,4,0
1197,1198,8.7,3.98,0.8,High,1,1,1,0
1198,1199,8.5,3.19,0.6,High,7,9,9,0
1199,1200,6.5,2.91,0.9,Medium,5,7,3,0

In [20]:
#Vamos a crear un archivo csv y guardarlo en la carpeta del proyecto. 

adolescentes.to_csv("adolescentes.csv", index=False)
comportamiento_uso.to_csv("comportamiento_uso.csv", index=False)
salud_rendimiento.to_csv("salud_rendimiento.csv", index=False)

In [21]:
#Vamos a comprobar que se hayan creado en la carpeta del proyecto. 

import os
os.listdir()

['.git',
 'adolescentes.csv',
 'bienestar.csv',
 'comportamiento_uso.csv',
 'Notebook.ipynb',
 'README.md',
 'salud_rendimiento.csv',
 'Teen_Mental_Health_Dataset.csv',
 'uso_redes.csv']